import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function ensureCertsExist() {
	const certsPath = path.resolve(__dirname, 'certs');
	const keyPath = path.join(certsPath, 'key.pem');
	const certPath = path.join(certsPath, 'cert.pem');

	// Wait for certificates to exist (generated by backend)
	const maxWaitTime = 30000; // 30 seconds
	const checkInterval = 500; // Check every 500ms
	const startTime = Date.now();

	while (!fs.existsSync(keyPath) || !fs.existsSync(certPath)) {
		if (Date.now() - startTime > maxWaitTime) {
			throw new Error('Timeout waiting for SSL certificates. Make sure backend service is running and has generated certificates.');
		}

		// Sleep for checkInterval
		const sleepUntil = Date.now() + checkInterval;
		while (Date.now() < sleepUntil) {
			// Busy wait
		}
	}

	console.log('✅ SSL certificates found and ready.');
}
